# Generated by Django 2.0.6 on 2018-06-16 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('province', models.CharField(max_length=32)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.Dept')),
            ],
            options={
                'db_table': 'employeeb',
            },
        ),
    ]
