# Generated by Django 2.0.6 on 2018-06-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
