# Generated by Django 2.0.6 on 2018-06-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_employeeb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
