# Generated by Django 2.0.6 on 2018-06-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180614_1008'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
